### ISSUE TITLE
bad transparency mask 这个需要怎么调整？

### ISSUE THREAD

**Issue by kingwgj** [Jianghuchengphilip/Generate-NFT#5]
我把一组小狗图片，元素有 如 身体，尾巴，XXXX 等
按身体、尾巴排序是可以正常生成图片的。
但是按尾巴、身体 生成就不行了。
因为尾巴是在身体的下面，需要放在id=1的位置上面。
报错误如下：
Traceback (most recent call last):
  File "Interface.py", line 82, in <module>
  File "Interface.py", line 70, in main
  File "nft.py", line 104, in generate_images
  File "nft.py", line 54, in generate_single_image
  File "PIL\Image.py", line 1557, in paste
ValueError: bad transparency mask

**Comment by Jianghuchengphilip** [comment]
我猜测你的尾巴图像和身体图像尺寸不相同，请注意这个软件不兼容8位的小型png只兼容32位。请检查~😄
